apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deploy
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: hello-world
        image: 969682547877.dkr.ecr.ap-south-1.amazonaws.com/eks-git:v7
        ports:
        - containerPort: 3000
